import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from './components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Jar Pages</title>
        <meta name="description" content="Generated by humans and yerba" />
      </Head>
      <Navbar/>
      <main className={styles.main}>
          <HomeContent/>
      </main>
    </>
  )
}

function HomeContent() {

  return (
    <div className={styles.homeContent}>
      <h1>
        Beginning
      </h1>
      
    </div>
  )
}
